apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beatstape-profile-management-s
  name: beatstape-profile-management-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beatstape-profile-management-s
  strategy: {}
  template:
    metadata:
      labels:
        app: beatstape-profile-management-s
    spec:
      containers:
      - image: beatstape-profile-management-s
        name: beatstape-profile-management-s
        ports:
          - containerPort: 8080
        resources: {}
status: {}
