package com.joyreaim.beatstape.profilemanagement.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "beatstape_profile")
public class Profile {

    @DynamoDBHashKey(attributeName = "id")
    public String id;

    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.ALWAYS)
    public Long lastUpdate;

    @DynamoDBAttribute(attributeName = "bio")
    public String bio;

    @DynamoDBAttribute(attributeName = "userName")
    public String userName;

    @DynamoDBAttribute(attributeName = "artistName")
    private String artistName;

    @DynamoDBAttribute(attributeName = "picture")
    private String picture;

    @DynamoDBAttribute(attributeName = "tagPreferences")
    private List<String> tagPreferences;
}
